name: 3ladeMapEngine
version: '${project.version}'
main: ladeEngine.MapEngine
api-version: 1.19
authors: [ 3lade ]
depend:
  - ProtocolLib
description: GameEngine on minecraft map
commands:
  meapps:
    description: show all apps