name: 3ladeMapEngine
version: '${project.version}'
main: ladeEngine.MapEngine
api-version: 1.20
authors: [ 3lade ]
description: GameEngine on minecraft map
commands:
  meapps:
    description: show all apps